#!/usr/bin/env python3
"""Helper script for prd-writer on issue #311."""
import subprocess
import json
import sys

REPO = "m-a-operating-system/ai-coding-standards2"
ISSUE = "311"


def gh_api(endpoint, method="GET", data=None):
    cmd = ["gh", "api", endpoint]
    if method != "GET":
        cmd += ["--method", method]
    if data:
        cmd += ["--input", "-"]
    result = subprocess.run(
        cmd,
        input=json.dumps(data).encode() if data else None,
        capture_output=True,
    )
    if result.returncode != 0:
        print("ERROR:", result.stderr.decode(), file=sys.stderr)
        sys.exit(1)
    if result.stdout:
        return json.loads(result.stdout)
    return None


def check_snapshot():
    comments = gh_api(f"repos/{REPO}/issues/{ISSUE}/comments?per_page=100")
    for c in comments:
        if "ai-agile/snapshot/v1 by 01_product_docs/prd-writer" in c["body"]:
            return True
    return False


def post_snapshot(orig_title, orig_body):
    body = f"""<!-- ai-agile/snapshot/v1 by 01_product_docs/prd-writer -->
## Original issue (snapshot before PRD rewrite)

**Original title:** {orig_title}

**Original body:**

{orig_body}"""
    gh_api(
        f"repos/{REPO}/issues/{ISSUE}/comments",
        method="POST",
        data={"body": body},
    )
    print("Snapshot posted.")


def update_issue_body(title, orig_body):
    new_body = f"""<!-- ai-agile/artefact/v1 by 01_product_docs/prd-writer -->

{orig_body}

---
*Pre-existing specification preserved. Governance elements added by prd-writer.*"""
    gh_api(
        f"repos/{REPO}/issues/{ISSUE}",
        method="PATCH",
        data={"title": title, "body": new_body},
    )
    print("Issue body updated.")


def post_closing_announcement():
    body = """<!-- ai-agile/announcement/v1 by 01_product_docs/prd-writer -->
```json
{
  "session_id": "ais-v1-01-product-docs-prd-writer-issue-311",
  "agent": "01_product_docs/prd-writer",
  "phase": "end",
  "ended_at": "2026-08-18T01:30:00Z",
  "outcome": "review",
  "summary": "Pre-specified issue (5/6 signals). Governance header added to body; 4 existing Gherkin scenarios exceed bug minimum of 1. Title already has correct [BUG] prefix. Awaiting prd-writer:approved.",
  "branch": "issue-311"
}
```

---
_Generated by [Claude Code](https://claude.ai/code)_"""
    gh_api(
        f"repos/{REPO}/issues/{ISSUE}/comments",
        method="POST",
        data={"body": body},
    )
    print("Closing announcement posted.")


if __name__ == "__main__":
    action = sys.argv[1] if len(sys.argv) > 1 else "check"

    if action == "check_snapshot":
        has_snap = check_snapshot()
        print("HAS_SNAPSHOT:", has_snap)

    elif action == "post_snapshot":
        issue = gh_api(f"repos/{REPO}/issues/{ISSUE}")
        orig_title = issue["title"]
        orig_body = issue["body"] or ""
        has_snap = check_snapshot()
        if not has_snap:
            post_snapshot(orig_title, orig_body)
        else:
            print("Snapshot already exists, skipping.")

    elif action == "update_body":
        issue = gh_api(f"repos/{REPO}/issues/{ISSUE}")
        orig_title = issue["title"]
        orig_body = issue["body"] or ""
        if "ai-agile/artefact/v1 by 01_product_docs/prd-writer" in orig_body:
            print("Governance header already present, skipping body update.")
        else:
            update_issue_body(orig_title, orig_body)

    elif action == "post_closing":
        post_closing_announcement()

    elif action == "all":
        issue = gh_api(f"repos/{REPO}/issues/{ISSUE}")
        orig_title = issue["title"]
        orig_body = issue["body"] or ""

        has_snap = check_snapshot()
        if not has_snap:
            post_snapshot(orig_title, orig_body)
        else:
            print("Snapshot already exists.")

        if "ai-agile/artefact/v1 by 01_product_docs/prd-writer" not in orig_body:
            update_issue_body(orig_title, orig_body)
        else:
            print("Governance header already present.")

        post_closing_announcement()
