"""AS-3 -- a command names something; it does not do something (issue #407).

PRODUCT.md's own test for AS-3: "Every command file resolves to a generated
wrapper or a single named target. A command containing a numbered procedure, a
conditional, or a retry loop is a test failure."

Twelve `/maos-*` commands are generated from `pipeline.json` and carry the
generator's marker. Four are hand-authored -- `maos-merge`,
`maos-new-branch-pr`, `maos-rebaseline`, `maos-run` -- and each must name a
single script and pass its arguments through, with the procedure itself living
in `.github/scripts/` where it can be tested.
"""
import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).parent.parent
COMMANDS = REPO_ROOT / ".claude" / "commands"
SCRIPTS = REPO_ROOT / ".github" / "scripts"

GENERATED_MARKER = (
    "<!-- generated by scripts/generate_slash_commands.py -- "
    "do not edit; regenerated from pipeline.json -->"
)

# Each hand-authored command and the single script it names.
HAND_AUTHORED = {
    "maos-merge.md": "merge-pr.sh",
    "maos-new-branch-pr.md": "new-branch-pr.sh",
    "maos-rebaseline.md": "rebaseline-branch.sh",
    "maos-run.md": "drive-item.sh",
}


def _hand_authored_files():
    return sorted(
        p for p in COMMANDS.glob("maos-*.md")
        if GENERATED_MARKER not in p.read_text()
    )


class TestOnlyTheKnownFourAreHandAuthored:
    def test_the_set_has_not_grown(self):
        assert {p.name for p in _hand_authored_files()} == set(HAND_AUTHORED), (
            "a new hand-authored maos-* command needs an entry here and a script "
            "of its own -- AS-3 admits no third kind of command"
        )


@pytest.mark.parametrize("name,script", sorted(HAND_AUTHORED.items()))
class TestEachHandAuthoredCommandNamesASingleScript:
    def test_the_script_it_names_exists(self, name, script):
        assert (SCRIPTS / script).is_file(), (
            f"{name} names {script}, which does not exist"
        )

    def test_the_command_names_that_script(self, name, script):
        assert script in (COMMANDS / name).read_text()

    def test_it_invokes_no_other_pipeline_script(self, name, script):
        """A command running two scripts is sequencing them -- that is a
        procedure, and it belongs in one script instead. Prose may still
        mention another script by name (which one this one hands off to)."""
        blocks = "\n".join(
            re.findall(r"```bash\n(.*?)```", (COMMANDS / name).read_text(), re.DOTALL)
        )
        others = {
            other.name for other in SCRIPTS.glob("*.sh")
            if other.name != script and other.name in blocks
        }
        assert not others, f"{name} also invokes {sorted(others)}"

    def test_it_contains_no_numbered_procedure(self, name, script):
        text = (COMMANDS / name).read_text()
        numbered = re.findall(r"^\s*\d+\.\s+\*\*", text, re.M)
        assert not numbered, (
            f"{name} contains a numbered procedure ({len(numbered)} step(s)); "
            "the steps belong in .github/scripts/, where they can be tested"
        )

    def test_it_contains_no_shell_conditional_or_loop(self, name, script):
        """The one conditional a wrapper may carry is locating its own script
        in the two supported checkout layouts."""
        text = (COMMANDS / name).read_text()
        for block in re.findall(r"```bash\n(.*?)```", text, re.DOTALL):
            body = "\n".join(
                line for line in block.splitlines()
                if not line.lstrip().startswith("[ -f ")
            )
            for keyword in ("if ", "elif ", "for ", "while ", "case "):
                assert keyword not in body, (
                    f"{name} has a shell {keyword.strip()} in a command block; "
                    "logic belongs in the script it names"
                )

    def test_it_tells_the_reader_not_to_reimplement_the_script(self, name, script):
        text = " ".join((COMMANDS / name).read_text().lower().split())
        assert "do not interpret, second-guess, or reimplement its logic" in text, (
            f"{name} must tell the reader to run the script rather than "
            "re-derive what it does"
        )


class TestTheExtractedScriptsAreRealScripts:
    @pytest.mark.parametrize("script", sorted(set(HAND_AUTHORED.values())))
    def test_it_parses(self, script):
        import subprocess
        res = subprocess.run(
            ["bash", "-n", str(SCRIPTS / script)], capture_output=True, text=True,
        )
        assert res.returncode == 0, f"{script} does not parse: {res.stderr}"

    @pytest.mark.parametrize("script", sorted(set(HAND_AUTHORED.values())))
    def test_it_fails_closed(self, script):
        """STD-ARCH-014: `set -e` so a failed step stops the script instead of
        carrying on to produce a success-shaped result."""
        assert "set -euo pipefail" in (SCRIPTS / script).read_text()


class TestGateCrossingWasNotAutomated:
    """MI-7: a gate is crossed by a person's own label, or by the orchestrator
    recording a confirmation the driver relayed -- never by a script."""

    def test_the_drive_script_never_writes_a_label(self):
        # Comments explain the rule and echo lines tell the person what to do
        # next; neither is the script acting. What must not appear is an
        # executed label write or gate confirmation.
        text = "\n".join(
            line for line in (SCRIPTS / "drive-item.sh").read_text().splitlines()
            if not line.lstrip().startswith(("#", "echo ", 'echo "', "printf "))
        )
        for forbidden in (
            "gh issue edit", "--add-label", "--confirm-gate", "approved",
        ):
            assert forbidden not in text, (
                f"drive-item.sh references {forbidden!r}; crossing a gate is "
                "never something a script may do on its own (MI-7)"
            )

    def test_the_drive_script_stops_at_a_halt(self):
        text = (SCRIPTS / "drive-item.sh").read_text()
        assert "review|blocked|failed" in text
        assert "exit 2" in text

    def test_the_command_relays_the_decision_rather_than_making_it(self):
        text = (COMMANDS / "maos-run.md").read_text()
        assert "--confirm-gate" in text, (
            "maos-run.md must tell the driver how to relay a human approval"
        )
        assert "never write the label yourself" in text
