#!/usr/bin/env python3
"""Generate .claude/commands/maos-*.md slash commands from pipeline.json.

Two command files per non-script agent (issue #402):
  maos-{short}.md    -- spawns the step as a real subprocess (headless path).
  maos-{short}-i.md  -- resolve-only mode; a person and the chat-AI work
                         through the step's instructions directly.
Creates missing files, updates changed files, and deletes stale generated
files for removed agents.

Only files THIS script produced are ever deleted -- they carry GENERATED_MARKER
on the first line. Hand-authored maos-* commands (e.g. maos-merge,
maos-new-branch-pr, maos-rebaseline, maos-run) have no marker and are left
untouched, so they survive a sync run even though they map to no pipeline
agent.

Usage:
    python3 scripts/generate_slash_commands.py
"""
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
PIPELINE_JSON = REPO_ROOT / "pipeline" / "pipeline.json"
COMMANDS_DIR = REPO_ROOT / ".claude" / "commands"

# Marker identifying a file this generator owns. Only marked files are eligible
# for deletion when their agent leaves the pipeline; unmarked (hand-authored)
# commands are never touched.
GENERATED_MARKER = "<!-- generated by scripts/generate_slash_commands.py -- do not edit; regenerated from pipeline.json -->"

SUBPROCESS_TEMPLATE = """\
# {title}

Run the `{agent}` pipeline agent as a real subprocess, spawned by the
orchestrator exactly as the headless (GitHub Actions) path does -- native
`--allowedTools` enforcement, nothing emulated (MI-3). {description}.

This command never applies labels, posts artefacts, or performs the step's
own work -- the orchestrator does that, in `pipeline_orchestrator.py`, the
same as it does headless (see `/maos-run`'s core rule).

## Input

`$ARGUMENTS` — GitHub issue or PR number (e.g. `42`)

## Instructions

1. Detect the repo and the orchestrator script path:
   ```bash
   REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner)
   SCRIPT=pipeline/pipeline_orchestrator.py
   [ -f "$SCRIPT" ] || SCRIPT=ai-coding-standards2/pipeline/pipeline_orchestrator.py
   ```
2. Make `{agent}` eligible this tick even if it is not the pipeline's natural
   next step — a manual override that bypasses only the trigger-label check;
   unmet dependencies still block it (harmless if it's already eligible):
   ```bash
   gh issue edit $ARGUMENTS --repo "$REPO" --add-label "{agent}:requested"
   ```
3. Run one orchestrator tick scoped to this issue — this spawns `{agent}` as
   a real subprocess with native `--allowedTools`, identical to the headless
   path, and performs every label transition, artefact comment, and commit
   itself:
   ```bash
   python3 "$SCRIPT" --repo "$REPO" --issue $ARGUMENTS
   ```
4. Report what happened from the resulting labels — advanced, reached a
   human gate, or halted. If `{agent}:requested` is still present afterward,
   the step was not eligible this tick (most likely unmet dependencies or an
   existing terminal status) — check labels, or use `/unblock-agent` /
   `/retry-agent` first.

{marker}
"""

INTERACTIVE_TEMPLATE = """\
# {title}

Work through the `{agent}` pipeline step's own instructions directly, with
the chat-AI, in this session. This is not an agent invocation (MI-3,
"Headless and interactive") — no subprocess is spawned, and no tool-access
enforcement is attempted; this session's own normal permissions apply
throughout. {description}.

The orchestrator still performs every label transition, artefact comment,
body write, and commit — never this command by hand (same core rule as
`/maos-run` and `/maos-{short}`). Two phases, run in order, in one sitting.

## Input

`$ARGUMENTS` — GitHub issue or PR number (e.g. `42`)

## Phase 1 — resolve the step's instructions

1. Detect the repo and the orchestrator script path:
   ```bash
   REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner)
   SCRIPT=pipeline/pipeline_orchestrator.py
   [ -f "$SCRIPT" ] || SCRIPT=ai-coding-standards2/pipeline/pipeline_orchestrator.py
   ```
2. Make `{agent}` eligible even if it is not the pipeline's natural next step
   (stays in place until Phase 2 consumes it):
   ```bash
   gh issue edit $ARGUMENTS --repo "$REPO" --add-label "{agent}:requested"
   ```
3. Resolve the step's prompt, tool context, and scratch directory —
   resolve-only mode; mutates no GitHub state:
   ```bash
   RESOLVED=$(python3 "$SCRIPT" --repo "$REPO" --agent {agent} --issue $ARGUMENTS --print-prompt)
   AI_AGILE_SCRATCH=$(echo "$RESOLVED" | jq -r '.env.AI_AGILE_SCRATCH')
   AI_AGILE_SCRATCH="$AI_AGILE_SCRATCH" bash .github/scripts/scratch-setup.sh
   ```
   Export `AI_AGILE_SCRATCH` for the rest of this session so the step's own
   snippets resolve it rather than falling back to a shared `/tmp`.
4. Follow the printed prompt's instructions **directly, as this session** —
   not by spawning a subagent. This session's own permissions and
   confirmations apply throughout; nothing scopes or restricts tool access
   on its behalf.
5. When you reach the step's terminal instruction, write
   `$AI_AGILE_SCRATCH/result.json` yourself, exactly per the prompt's own
   "write your result" instructions — `outcome`, `summary`, `output`,
   `label_requests`, `body_write`, etc., precisely as a spawned agent would.

## Phase 2 — apply the result

6. Hand the written result to the orchestrator to apply. This runs the same
   eligibility check and the same :wip/announcement/artefact/label/
   body-write/post_steps handling a real run would, so GitHub state and the
   audit trail cannot drift between the two paths (MI-3) — the only
   difference recorded is attribution: a person performed this activity, not
   a spawned agent.
   ```bash
   python3 "$SCRIPT" --repo "$REPO" --agent {agent} --issue $ARGUMENTS --interactive-result
   ```
7. Report what happened from the resulting labels. If `{agent}:requested` is
   still present afterward, nothing was applied — the orchestrator's own
   output names why (an invalid/missing `result.json`, or an eligibility
   check that no longer passes); fix that and re-run step 6 rather than
   redoing Phase 1.
8. Remove the scratch directory, even if an earlier step halted:
   ```bash
   [ -n "${{AI_AGILE_SCRATCH:-}}" ] && AI_AGILE_SCRATCH="$AI_AGILE_SCRATCH" bash .github/scripts/scratch-teardown.sh
   ```

{marker}
"""


def _short_name(agent_path: str) -> str:
    """'03_execute/pr-reviewer' → 'pr-reviewer'"""
    return agent_path.split("/")[-1]


def _first_sentence(text: str) -> str:
    """Return the first sentence of a description string."""
    sentence = re.split(r"\.\s", text.strip())[0].rstrip(".")
    # Hard-wrap at 90 chars so the heading stays readable
    if len(sentence) > 90:
        sentence = sentence[:87] + "…"
    return sentence


def _render_subprocess(entry: dict) -> str:
    agent = entry["agent"]
    short = _short_name(agent)
    description = _first_sentence(entry.get("description", ""))
    return SUBPROCESS_TEMPLATE.format(
        marker=GENERATED_MARKER,
        title=f"maos-{short}",
        description=description,
        agent=agent,
    )


def _render_interactive(entry: dict) -> str:
    agent = entry["agent"]
    short = _short_name(agent)
    description = _first_sentence(entry.get("description", ""))
    return INTERACTIVE_TEMPLATE.format(
        marker=GENERATED_MARKER,
        title=f"maos-{short}-i",
        description=description,
        agent=agent,
        short=short,
    )


def main() -> int:
    pipeline = json.loads(PIPELINE_JSON.read_text())

    # Agent-type entries only — script-type steps (create-pr, ci-gate) are
    # not interactively invokable and get no slash command.
    agents = [
        step
        for flow in (pipeline.get("flows") or {}).values()
        for step in (flow.get("steps") or [])
        if step.get("type", "agent") == "agent"
    ]

    COMMANDS_DIR.mkdir(parents=True, exist_ok=True)

    # Expected filename → (pipeline entry, renderer). Two files per agent
    # (issue #402): the subprocess-spawn command and its "-i" resolve-only
    # counterpart.
    expected: dict[str, tuple] = {}
    for e in agents:
        short = _short_name(e["agent"])
        expected[f"maos-{short}.md"] = (e, _render_subprocess)
        expected[f"maos-{short}-i.md"] = (e, _render_interactive)

    created, updated, deleted = [], [], []

    for fname, (entry, render) in expected.items():
        content = render(entry)
        dest = COMMANDS_DIR / fname
        if not dest.exists():
            dest.write_text(content)
            created.append(fname)
        elif dest.read_text() != content:
            dest.write_text(content)
            updated.append(fname)

    # Remove stale GENERATED files for agents no longer in pipeline.json. Only
    # files carrying GENERATED_MARKER are ours to delete; hand-authored
    # maos-* commands (no marker) are preserved.
    for existing in sorted(COMMANDS_DIR.glob("maos-*.md")):
        if existing.name in expected:
            continue
        try:
            is_generated = GENERATED_MARKER in existing.read_text()
        except OSError:
            is_generated = False
        if is_generated:
            existing.unlink()
            deleted.append(existing.name)

    if created:
        print(f"Created:  {', '.join(sorted(created))}")
    if updated:
        print(f"Updated:  {', '.join(sorted(updated))}")
    if deleted:
        print(f"Deleted:  {', '.join(sorted(deleted))}")
    if not created and not updated and not deleted:
        print("Slash commands already up-to-date.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
